### ISSUE TITLE
Советы для начала с nim

### ISSUE THREAD

**Issue by DevMuv** [yglukhov/nim-sdl-template#2]
Просмотрел язык, прочитал manual, запускал данный проект - работает на fedora и на андроид. Вобщем, понял. Язык - вещь! Хочу на нем начинать писать игрушку. Посмотрел ваше видео в ютубе. Несовсем понятно какие packagы вы используете. Как вообще экспортировать с After Effects? Много чего непонятно, особенно как вообще начинать.

**Comment by yglukhov** [comment]
@DevMuv, общие вопросы о том как начать с Nim лучше задавать на форуме. Далее следует ИМХО. Прежде чем писать игру на Nim, желательно понимать, как она пишется на другом языке, к примеру на C++. В nimble есть несколько оберток над библиотеками для игр. Вчастности, urhonimo - обертка для Urho3D. В своей игре мы используем [nimx](https://github.com/yglukhov/nimx), как UI библиотеку, и [rod](https://github.com/yglukhov/rod), как 3D/2D движок. Недостаток их в отсутствии документации и в том, что они все еще в глубокой разработке =). Преимущество в том, что они на 100% Nim, и могут собираться в JavaScript. В rod есть экспортер для After Effects.

Повторюсь, трекер не предназначен для советов новичкам, и на форуме вам ответит больше людей. Тему закрываю. Удачи!
